# Generated by Django 4.2.9 on 2024-01-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dish", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="structure",
            name="Weight",
            field=models.IntegerField(
                default=None, null=True, verbose_name="Колличество блюд"
            ),
        ),
    ]
